name: Trigger auto deployment for xray-analyzer-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/xray-analyzer-backend-AutoDeployTrigger-154bb395-125a-407a-8986-207524096532.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.XRAYANALYZERBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.XRAYANALYZERBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.XRAYANALYZERBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}backend
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: xrayregistry1113.azurecr.io
          registryUsername: ${{ secrets.XRAYANALYZERBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.XRAYANALYZERBACKEND_REGISTRY_PASSWORD }}
          containerAppName: xray-analyzer-backend
          resourceGroup: xray-analyzer-rg
          imageToBuild: xrayregistry1113.azurecr.io/xray-analyzer-backend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


